---
title: "Final Project"
author: "Mengqi Zhu & Shuang Wu & Yutian Mu & Dong Yuan"
date: "November 22nd 2017"
output: 
   html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(readr)
library(janitor)
library(lubridate)
library(stringr)
library(chron)
library(forcats)
```

#Description
```{r}
#Read and clean data
nyc_bus <- 
  read_csv("./Bus_Breakdown_and_Delays.csv") %>%
  clean_names() 

#Delay Clean
nyc_bus_delay <-
  nyc_bus %>%
  filter(grepl(pattern = '^[0-9]+', how_long_delayed, perl = TRUE) == TRUE) %>%
  select(busbreakdown_id,how_long_delayed) %>%
  mutate(how_long_delayed = tolower(how_long_delayed)) 

nyc_bus_delay_hour <-
  nyc_bus_delay %>%
  filter(grepl("h", how_long_delayed, ignore.case = T)== TRUE) %>%
  mutate(how_long_delayed 
         =
           ifelse(grepl("1 hr 30", how_long_delayed)== TRUE,"90",
                  ifelse(grepl("1 hr 45min", how_long_delayed)== TRUE,"105",
                         ifelse(grepl("1 hr 30min", how_long_delayed)== TRUE,"90",
                                ifelse(grepl("1hour", how_long_delayed)== TRUE,"60",
                                       ifelse(grepl("1 hour", how_long_delayed)== TRUE,"60",
                                              ifelse(grepl("1 h", how_long_delayed)== TRUE,"60",
                                                     ifelse(grepl("1h", how_long_delayed)== TRUE,"60",
                                                            ifelse(grepl("1/2", how_long_delayed)== TRUE,"30",
                                                                ifelse(grepl("2", how_long_delayed)== TRUE,"120",
                                                                       ifelse(grepl("4", how_long_delayed)== TRUE,"240","NA")))))))))))

nyc_bus_delay_min <- nyc_bus_delay %>%
  filter(grepl("h", how_long_delayed, ignore.case = T)== FALSE) %>%
  mutate(how_long_delayed = substr(how_long_delayed,1,2)) %>%
  mutate(how_long_delayed = sub(pattern = 'm',replacement = '', how_long_delayed),
         how_long_delayed = sub(pattern = '/',replacement = '', how_long_delayed),
         how_long_delayed = sub(pattern = ':',replacement = '', how_long_delayed),
         how_long_delayed = sub(pattern = 'o',replacement = '', how_long_delayed),
         how_long_delayed = sub(pattern = '-',replacement = '', how_long_delayed),
         how_long_delayed = sub(pattern = '02',replacement = '2', how_long_delayed),
         how_long_delayed = sub(pattern = '07',replacement = '7', how_long_delayed),
         how_long_delayed = sub(pattern = '00',replacement = '0', how_long_delayed),
         how_long_delayed = sub(pattern = '08',replacement = '8', how_long_delayed),
         how_long_delayed = sub(pattern = '01',replacement = '1', how_long_delayed),
         how_long_delayed = sub(pattern = '\\.',replacement = '', how_long_delayed)) %>%
  mutate(how_long_delayed = str_trim(how_long_delayed))

nyc_bus_delay <- rbind(nyc_bus_delay_hour,nyc_bus_delay_min)

nyc_bus <- nyc_bus %>% 
  select(- how_long_delayed) 
nyc_bus <- merge(nyc_bus,nyc_bus_delay, by.x = "busbreakdown_id", by.y = "busbreakdown_id", all = TRUE) %>%
  mutate(how_long_delayed = as.numeric(how_long_delayed))

#Company name clean
nyc_bus <-
  nyc_bus %>%
  filter(!is.na(boro)) %>%  #filter NAs
  mutate(bus_company_name = tolower(bus_company_name),
         company_name = str_sub(bus_company_name,1,5)) %>%   #find the unique company name
  select(school_year:bus_company_name,company_name,everything())
```

```{r}
#Count over time
nyc_bus %>%
  separate(occurred_on, into = c("date", "time", "am_pm"), sep = " ") %>%
  mutate(datetime = format(strptime(str_c(time, am_pm, sep = " "), "%I:%M:%S %p"), "%H:%M:%S")) %>%
  count(datetime, boro) %>%
  rename(delay_count = n) %>%
  ggplot(aes(x = datetime, y = delay_count, fill = boro, color = boro)) +
  geom_point() +
  geom_smooth() +
  theme(text = element_text(size = 10),
        axis.text.x = element_text(angle = 90, hjust = 1),
        plot.title = element_text(hjust = 0.5)) +
  scale_x_discrete(breaks = c("00:00:00", "06:00:00", "12:00:00", "18:00:00"))
```

```{r}
#Number of Breakdown by boros
nyc_bus %>%
  filter(breakdown_or_running_late == "Breakdown") %>%
  group_by(boro) %>% 
  count() %>% 
  ungroup() %>% 
  mutate(boro = as.factor(boro),
         boro = fct_reorder(boro,n)) %>% 
  ggplot(aes(x = boro, y = n, fill = boro)) +
  geom_bar(stat = "identity",alpha = 0.8) +
  theme(axis.text.x = element_text(angle = 90),
        text = element_text(size = 10),
        plot.title = element_text(hjust = 0.5)) +
   labs(y = "number of breakdown", title = "Number of Breakdown by boros")
```


```{r summary_function}
#Top routes where breakdowns or delays occur
summary_by_total <- function(data){
  list(variable = colnames(data),
       num_obs = rep(nrow(data), ncol(data)),
       mean = apply(data, 2, mean),
       sd = apply(data, 2, sd),
       min = apply(data, 2, min),
       median = apply(data, 2, median),
       max = apply(data, 2, max)) %>%
    as.tibble()
}
```

```{r summary_routes_breakdown}
nyc_bus %>%
  filter(breakdown_or_running_late == "Breakdown") %>%
  group_by(route_number) %>%
  summarize(breakdown = n()) %>%
  select(breakdown) %>%
  summary_by_total()

nyc_bus %>%
  filter(breakdown_or_running_late == "Running Late") %>%
  group_by(route_number) %>%
  summarize(delay = n()) %>%
  select(delay) %>%
  summary_by_total()
```
There are 11748 routes where breakdowns occur. We choose the most common ones with more than 200 breakdowns and make a barplot.

```{r top_routes}
#top routes with breakdown
nyc_bus %>%
  filter(breakdown_or_running_late == "Breakdown") %>%
  group_by(route_number) %>%
  summarize(n_route = n()) %>%
  ungroup() %>%
  mutate(route_rank=min_rank(desc(n_route))) %>%
  filter(route_rank <= 10) %>%
  mutate(route_number = fct_reorder(route_number, n_route)) %>%
  ggplot(aes(x = route_number, y = n_route)) +
  geom_bar(stat = "identity", fill = "blue", alpha = .6) +
  coord_flip() +
  labs(title = "Top 10 routes where breakdowns occur") +
  theme(axis.text.x = element_text(angle = 90),
        text = element_text(size = 10),
        plot.title = element_text(hjust = 0.5))
#top routes with running
nyc_bus %>%
  filter(breakdown_or_running_late == "Running Late") %>%
  group_by(route_number) %>%
  summarize(n_route = n()) %>%
  ungroup() %>%
  mutate(route_rank=min_rank(desc(n_route))) %>%
  filter(route_rank <= 10) %>%
  mutate(route_number = fct_reorder(route_number, n_route)) %>%
  ggplot(aes(x = route_number, y = n_route)) +
  geom_bar(stat = "identity", fill = "blue", alpha = .6) +
  coord_flip() +
  labs(title = "Top 10 routes where delay occur") +
  theme(axis.text.x = element_text(angle = 90),
        text = element_text(size = 10),
        plot.title = element_text(hjust = 0.5))
```



```{r reason_breakdown}
# Main reasons for school bus breakdowns and delays
reason_count_break = nyc_bus %>%
  filter(breakdown_or_running_late == "Breakdown") %>%
  group_by(reason) %>%
  filter(!is.na(reason))%>%
  summarize(n_reason = n()) %>%
  ungroup() %>%
  arrange(n_reason)
reason_count_break

reason_count_break %>%
  mutate(reason = fct_reorder(reason, n_reason)) %>%
  ggplot(aes(x = reason, y = n_reason)) +
  geom_bar(stat = "identity", fill = "blue", alpha = .6) +
  coord_flip() +
  labs(title = "Reasons for Breakdown") +
  theme(text = element_text(size = 10),
        plot.title = element_text(hjust = 0.5))

reason_count_delay = nyc_bus %>%
  filter(breakdown_or_running_late == "Running Late") %>%
  group_by(reason) %>%
  filter(!is.na(reason))%>%
  summarize(n_reason = n()) %>%
  ungroup() %>%
  arrange(n_reason)
reason_count_delay

reason_count_delay %>%
  mutate(reason = fct_reorder(reason, n_reason)) %>%
  ggplot(aes(x = reason, y = n_reason)) +
  geom_bar(stat = "identity", fill = "blue", alpha = .6) +
  coord_flip() +
  labs(title = "Reasons for Delay") +
  theme(text = element_text(size = 10),
        plot.title = element_text(hjust = 0.5))
```


```{r company_reason}
#breakdown/delay reasons for each company
nyc_bus %>%
  filter(breakdown_or_running_late == "Breakdown") %>%
  ggplot(aes(x = company_name , fill = reason)) + geom_bar() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Breakdown reasons for each company") +
  theme(text = element_text(size = 10),
        plot.title = element_text(hjust = 0.5))

nyc_bus %>%
  filter(breakdown_or_running_late == "Running Late") %>%
  ggplot(aes(x = company_name , fill = reason)) + geom_bar() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Breakdown reasons for each company") +
  theme(text = element_text(size = 10),
        plot.title = element_text(hjust = 0.5))
```


```{r}
#distribution of delay duration for each company
company_level <- 
  nyc_bus %>%
  filter(!is.na(how_long_delayed)) %>%
  group_by(company_name) %>%
  summarise(mean_duration = mean(how_long_delayed, na.rm = T)) %>%
  arrange(desc(mean_duration)) %>%
  pull(company_name)


nyc_bus %>%
  mutate(company_name = forcats::fct_relevel(company_name, company_level)) %>%
  filter(!is.na(how_long_delayed)) %>%
  ggplot(aes(x = company_name, y = how_long_delayed)) + 
  geom_boxplot(aes(fill = company_name), color = "blue", alpha = .5, outlier.size = 0.7) + 
  stat_summary(fun.y = median, geom = "point", color = "blue") +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none", 
        text = element_text(size = 10),
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Boxplot ofdelay duration for each company")
```

```{r}
#Relationship between delay duration and corresponded reason
nyc_bus %>%
  filter(!is.na(reason),
         !is.na(how_long_delayed)) %>%
  group_by(reason) %>%
  summarise(avg_time = mean(how_long_delayed)) %>%
  ggplot(mapping = aes(x = reason, y = avg_time, fill = reason)) + 
  geom_bar(stat= 'identity') +
  ggtitle("Average delay duration by reason") +
  labs(x = "Reason of delay", y = "Avergae delay duration") +
  theme(text = element_text(size = 10),
        axis.text.x = element_text(angle = 90, hjust = 1),
        plot.title = element_text(hjust = 0.5))
```

```{r}
#reaction time of notifying of each company
nyc_bus_reaction <- 
  nyc_bus %>%
  separate(occurred_on, into = c("occur_date", "occur_time", "occur_am_pm"), sep = " ") %>%
  separate(informed_on, into = c("inform_date", "inform_time", "inform_am_pm"), sep = " ") %>%
  mutate(occur_datetime = as.POSIXct(strptime(str_c(occur_time, occur_am_pm, sep = " "), "%I:%M:%S %p")),
         inform_datetime = as.POSIXct(strptime(str_c(inform_time, inform_am_pm, sep = " "), "%I:%M:%S %p")),
         reaction_time = inform_datetime - occur_datetime,
         is_same_time = as.Date(inform_date, format = "%m/%d/%Y") - as.Date(occur_date, format = "%m/%d/%Y"),
         occur_time = str_c(occur_date, occur_time, occur_am_pm, sep = " "),
         inform_time = str_c(inform_date, inform_time, inform_am_pm, sep = " "))

#inspect the cases that the occurred date and informed date are not the same
nyc_bus_reaction %>%
  select(occur_time, inform_time, reaction_time, is_same_time) %>%
  filter(is_same_time != 0) %>%
  arrange(is_same_time)
#the mean reaction time among the company occurred date and informed date are the same
nyc_bus_reaction %>%
  select(company_name, occur_time, inform_time, reaction_time, is_same_time) %>%
  filter(is_same_time == 0) %>%
  group_by(company_name) %>%
  summarise(mean_reaction = mean(reaction_time)) %>%
  arrange(desc(mean_reaction))
```
